FROM golang:1.24.3-alpine AS builder

ENV GO111MODULE=on
ENV CGO_ENABLED=0
ENV GOOS=linux

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o main .

FROM gcr.io/distroless/static-debian12

WORKDIR /

COPY --from=builder /app/main .

EXPOSE 8661

USER nonroot:nonroot

CMD ["./main"]